// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmsrhvdcrooepgjqgfiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtc3JodmRjcm9vZXBnanFnZml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzk1OTksImV4cCI6MjA2MzY1NTU5OX0.yRj2T_wpLYD9LNnX38fpUI2nqLHseyWwR31fzjKJWvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);